@baseUrl = http://localhost:3000

### Listar todos os gêneros
GET {{baseUrl}}/generos

### Obter um gênero por ID
GET {{baseUrl}}/generos/1

### Criar um novo gênero
POST {{baseUrl}}/generos
Content-Type: application/json

{
    "nome": "Ação"
}

### Atualizar um gênero
PUT {{baseUrl}}/generos/1
Content-Type: application/json

{
    "nome": "Ação e Aventura"
}

### Excluir um gênero
DELETE {{baseUrl}}/generos/1
